import { Inter, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ['400', '700'],
});

export const metadata = {
  title: "Omari Premium Water",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${lato.variable} antialiased`}>
          <Navbar/>
        {children}
      </body>
    </html>
  );
}
